version: '3'

services:
  apps:
    container_name : js_mongo_application
    restart : always
    build: .
    ports:
      - '80:3000'
    links:
      - mongo
  mongo:
    container_name : mongodb
    image: mongo
    ports:
      - '27017:27017'